# Generated by Django 5.0.2 on 2024-04-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_deliveryaddress_date_added_product_digital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_purchased',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
