# Generated by Django 5.0.2 on 2024-04-17 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_purchase_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
