# Generated by Django 5.0.2 on 2024-04-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_delete_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
