# Generated by Django 5.0.2 on 2024-04-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='purchase',
        ),
    ]
