# Generated by Django 5.0.2 on 2024-04-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_purchase_purchase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.AddField(
            model_name='product',
            name='purchase',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
