# Generated by Django 5.0.2 on 2024-04-17 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_delete_purchase_product_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='purchase',
        ),
    ]
