# Generated by Django 5.0.2 on 2024-04-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_product_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
