# Generated by Django 5.0.2 on 2024-04-17 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_product_purchase_orderitem_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='purchase',
        ),
    ]
