# Generated by Django 5.0.2 on 2024-04-17 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_remove_purchase_order_remove_purchase_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purchase',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.purchase'),
        ),
    ]
