# Generated by Django 5.0.2 on 2024-04-17 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_product_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purchase',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='store.purchase'),
        ),
    ]
